// <auto-generated /> //autogeneret kode som repræsenterer den aktuelle model for databasen. Det bruges af Entity Framework Core til at spore ændringer i modellen og generere migrations korrekt. Det er vigtigt at bemærke, at denne fil ikke bør redigeres manuelt, da den vil blive overskrevet af EF Core, når nye migrations oprettes.
using System;
using Microsoft.EntityFrameworkCore; //namespace for DbContext, ModelBuilder, DbContextOptions osv. bruges til at definere og konfigurere databasekonteksten og modellen
using Microsoft.EntityFrameworkCore.Infrastructure; //namespace for ModelSnapshot, som er en klasse der repræsenterer den aktuelle model for databasen. Det bruges af Entity Framework Core til at spore ændringer i modellen og generere migrations korrekt
using Microsoft.EntityFrameworkCore.Storage.ValueConversion; //namespace for ValueConverter, som bruges til at konvertere værdier mellem .NET typer og database typer. Det kan bruges i modelkonfigurationen til at specificere hvordan visse datatyper skal gemmes i databasen (f.eks. konvertere en enum til en string eller en bool til en int)
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata; //namespace for NpgsqlModelBuilderExtensions, som indeholder udvidelsesmetoder til ModelBuilder specifikt for PostgreSQL. I dette tilfælde bruges det til at konfigurere identitetskolonner (auto-incrementing primary keys) til at bruge PostgreSQL's "Identity by Default" strategi, hvilket er en anbefalet tilgang for at håndtere auto-incrementing keys i PostgreSQL
using treesy_backend.Data;

#nullable disable

namespace treesy_backend.Migrations
{
    [DbContext(typeof(TreesyDbContext))]
    partial class TreesyDbContextModelSnapshot : ModelSnapshot //nedarver fra ModelSnapshot, som er en klasse der repræsenterer den aktuelle model for databasen. Det bruges af Entity Framework Core til at spore ændringer i modellen og generere migrations korrekt. Denne klasse indeholder en BuildModel metode, som definerer strukturen af databasen (tabeller, kolonner, relationer, indekser osv.) baseret på de modelklasser og konfigurationer der er defineret i TreesyDbContext
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618 //pragma direktiv for at undertrykke advarsler om forældede API'er, som kan opstå i den autogenererede kode. Det sikrer at eventuelle brug af forældede metoder eller egenskaber i denne fil ikke vil generere advarsler under kompilering, hvilket er nyttigt fordi denne fil er autogenereret og ikke bør redigeres manuelt
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11") //angiver hvilken version af Entity Framework Core der blev brugt til at generere denne model snapshot. Det er nyttigt for at spore kompatibilitet og forstå hvilke funktioner og konventioner der gælder for denne model baseret på EF Core versionen
                .HasAnnotation("Relational:MaxIdentifierLength", 63); //angiver den maksimale længde for databaseobjektnavne (f.eks. tabelnavne, kolonnenavne, indeksnavne) i den underliggende database. I dette tilfælde er det sat til 63, hvilket er standard for PostgreSQL. Det betyder at alle objektnavne i databasen ikke må overstige 63 tegn, ellers vil der opstå en fejl ved oprettelse eller migrering af databasen

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder); //npgsqlmodelbuilderextensions er en klasse der indeholder udvidelsesmetoder til modelbuilder specifikt for PostgreSQL. UseIdentityByDefaultColumns er en metode der konfigurerer alle identitetskolonner (auto-incrementing primary keys) i modellen til at bruge PostgreSQL's "Identity by Default" strategi, hvilket er en anbefalet tilgang for at håndtere auto-incrementing keys i PostgreSQL. Det betyder at når en ny post indsættes i en tabel med en identitetskolonne, vil PostgreSQL automatisk generere en unik værdi for den kolonne, medmindre en værdi eksplicit angives i indsættelseskommandoen.

            modelBuilder.Entity("treesy_backend.Models.Customer", b => //Jeg konfigurerer Customer entiteten ved hjælp af Fluent API. Jeg definerer tabellens kolonner, datatyper, nøjagtighed, indekser og relationer. For eksempel definerer jeg Id som en Guid der genereres automatisk, Email som en required string med et unikt indeks, og StripeCustomerId som en string med et unikt indeks. Jeg definerer også relationerne mellem Customer og Order (en kunde kan have mange ordrer) og mellem Customer og Subscription (en kunde kan have mange abonnementer)
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text");

                    b.Property<int>("TotalTreesPlanted")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("StripeCustomerId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("treesy_backend.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountDkk")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("text");

                    b.Property<string>("StripeSessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Trees")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StripeSessionId")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("treesy_backend.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Billing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeSubscriptionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StripeSubscriptionId")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("treesy_backend.Models.Tree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("PlantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Trees");
                });

            modelBuilder.Entity("treesy_backend.Models.Order", b =>
                {
                    b.HasOne("treesy_backend.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("treesy_backend.Models.Subscription", b =>
                {
                    b.HasOne("treesy_backend.Models.Customer", "Customer")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("treesy_backend.Models.Tree", b =>
                {
                    b.HasOne("treesy_backend.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("treesy_backend.Models.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
